# Generated by Django 2.2.14 on 2021-03-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza_Rest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizes_pizzas', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('FamilyPizza', 'FamilyPizza')], default='S', max_length=200)),
                ('track_orders', models.CharField(choices=[('preparing', 'preparing'), ('delivered', 'delivered'), ('undelivered', 'undelivered')], default='preparing', max_length=100)),
                ('desired_pizzas', models.CharField(max_length=300)),
                ('number_pizzas', models.IntegerField(null=True)),
                ('status_customer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('orders', models.ManyToManyField(to='pizzaass.Pizza_Rest')),
            ],
        ),
    ]
