# Generated by Django 2.2.14 on 2021-03-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza_rest',
            name='info_customer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pizza_rest',
            name='status_customer',
            field=models.CharField(max_length=40),
        ),
    ]
