# Generated by Django 2.2.14 on 2021-03-19 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaass', '0002_auto_20210319_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='orders',
        ),
        migrations.AddField(
            model_name='customers',
            name='orders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pizzaass.Pizza_Rest'),
        ),
    ]
