# Generated by Django 2.2.14 on 2021-03-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaass', '0005_auto_20210319_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza_rest',
            name='orders_id',
        ),
    ]
